name: smart_local_notification_example
description: Example app demonstrating Smart Local Notification plugin features.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  smart_local_notification:
    path: ../
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.4
  permission_handler: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    # - assets/images/

  # Example audio files for testing
  # You should add actual audio files to assets/audio/ directory
