name: smart_local_notification
description: A Flutter plugin for native Android and iOS notifications with custom sound playback. Supports silent notifications with simultaneous custom audio playback.
version: 1.0.0
homepage: https://github.com/your-org/smart_local_notification

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.smart_local_notification
        pluginClass: SmartLocalNotificationPlugin
      ios:
        pluginClass: SmartLocalNotificationPlugin

topics:
  - notifications
  - audio
  - background
  - local-notifications
  - custom-sound
